public class ApproverUsers {
	@AuraEnabled
    @InvocableVariable(label='Records for Output' description='yourDescription' )
	public Id Segment_Lead;
	
    @AuraEnabled
    @InvocableVariable(label='Records for Output' description='yourDescription' )
	public Id Industry_Sales_Lead;
	
    @AuraEnabled
    @InvocableVariable(label='Records for Output' description='yourDescription' )
	public Id SVP_Sales;
    
    @AuraEnabled
    @InvocableVariable(label='Records for Output' description='yourDescription' )
	public Id SVP_Services;
	
    @AuraEnabled
    @InvocableVariable(label='Records for Output' description='yourDescription' )
	public Id Industry_President;
	
    @AuraEnabled
    @InvocableVariable(label='Records for Output' description='yourDescription' )
	public Id COO;
	
    @AuraEnabled
    @InvocableVariable(label='Records for Output' description='yourDescription' )
	public Id Services_Segment_Lead;
	
    @AuraEnabled
    @InvocableVariable(label='Records for Output' description='yourDescription' )
	public Double DealAcvUpto;    
}