@istest
public class BooleanExpressionResolverTest {

    @istest
    public static void evalTest(){
        Boolean result=False;
        Test.StartTest();
        result = BooleanExpressionResolver.eval('False');
        result = BooleanExpressionResolver.eval('Test');
        result = BooleanExpressionResolver.eval('True');
        Test.StopTest();
        Assert.areEqual(True, result);
    }
}