/**
* @description       : This is a Constant Utility class which contains all the hardcoded values to be used in the apex.
* @author            : Pankaj Kumar
* @last modified on  : 09-28-2023
* @last modified by  : Pankaj Kumar
* Modifications Log
* Ver   Date         Author         Modification
* 1.0   09-28-2023   Pankaj Kumar   Initial Version
**/
public class ConstantUtilityClass{
    
    public static final String NEXTYEARMULTIYEAR = 'NextYear_MultiYear';
    public static final String OPTYSTAGEPREFUNNEL = 'Pre-Funnel';
    public static final String BLANKVALUE = '';
    public static final Integer TWO= 2;
    public static final Integer ONE = 1;
    public static final String SINGLECONTRACT = 'Single Contract';
    public static final String SELECTBUNDLECODE = System.Label.Select_Bundle_Product_Code;
    public static final String AUTORENEWAL = 'Auto-Renewal';
}