@isTest
public class TestIdeaFactory {
	
    //public static Idea createOneIdea(string contactID, string communityID)
    //{
    	////Create an Idea
    	//Idea newIdea = createIdea(contactID, communityID);
        //return newIdea;
    //}

    //private static Idea createIdea(string contactID, string communityID)
    //{
        //Idea i = new Idea();
        //i.Title = 'Test Idea from Developer Console';
        //i.Body = 'This is a test from the developer console';
        //i.CommunityId = communityID;
        //i.CreatedById = contactID;
        //insert i;
        //return i;
    //}
}