@isTest
private class TestIdeaCreation {
	
    //static testmethod void TestCreateIdea()
    //{
        //Test.startTest();        
        //Idea newIdea1 = TestIdeaFactory.createOneIdea('00550000001PGfGAAW', '09a50000000Gz7PAAS');
        //Idea newIdea2 = TestIdeaFactory.createOneIdea(null, '09a500000000ANkAAM');
        //Idea newIdea3 = TestIdeaFactory.createOneIdea('00550000001PGfGAAW', '09a50000000Gz7UAAS');
        //Idea newIdea4 = TestIdeaFactory.createOneIdea(null, '09a50000000Gz7ZAAS');
        //Test.stopTest();
        
        
    //}
}